version: '3.3'
services:
    mongo:
        ports:
            - '27017:27017'
        container_name: mymongo
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=mypass
        image: mongo
        volumes:
            - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
